### ISSUE TITLE
Freezes under terraform-provider-helm

### ISSUE THREAD

**Issue by pib** [aslafy-z/helm-git#101]
So I know this isn't really your fault, since the helm spec says it's safe to assume HELM_BIN will be set properly, but when this plugin is used in Terraform via the helm provider, it freezes because HELM_BIN is incorrectly set to the terraform provider executable.

This happens because the provider embeds helm as a library and uses `os.Args[0]` for HELM_BIN. This issue will affect any plugin that relies on HELM_BIN.

I've already filed a issue with that provider: https://github.com/terraform-providers/terraform-provider-helm/issues/506

I figured it would be a good idea to create this issue here in case anyone else runs into the same issue that I did.

My current workaround is to patch helm-git-plugin.sh to set HELM_BIN to just be "helm" in the Dockerfile I'm using after installing the plugin:
```sh
sed -i '1 aHELM_BIN=helm' /var/lib/helm/plugins/helm-git/helm-git-plugin.sh
```

This just adds `HELM_BIN=helm` on the second line of the file, overriding any value that was provided before.

**Comment by aslafy-z** [comment]
Fixed as part of [`v0.8.0`](https://github.com/aslafy-z/helm-git/releases). Please have a try!
