### ISSUE TITLE
--debug flag sets helm_home to wrong value

### ISSUE THREAD

**Issue by jaroslaw-osmanski** [aslafy-z/helm-git#107]
helm diff --debug upgrade <RELEASE_NAME> <CHART_NAME>
`[debug] Created tunnel using local port: '52987'

[debug] SERVER: "127.0.0.1:52987"

Error: This command needs 1 argument: chart name
Error: plugin "helm-git" exited with error
Error: plugin "diff" exited with error` 

`helm diff upgrade flink-operator flink-operator-repo/flink-operator-chart` works.
helm_home here:
https://github.com/aslafy-z/helm-git/blob/417a2a54dd9634bf407ea505da42377b8e7868c5/helm-git-plugin.sh#L201 is being set to `Repository: repository RepositoryFile: repository/repositories.yaml Cache: repository/cache Stable CacheIndex: repository/cache/stable-index.yaml Starters: starters LocalRepository: repository/local Plugins: plugins`, which is very similar to `helm --debug home` but without HELM_HOME at first line.
 
helm version `Client: &version.Version{SemVer:"v2.16.3", GitCommit:"1ee0254c86d4ed6887327dabed7aa7da29d7eb0d", GitTreeState:"clean"}`

**Comment by aslafy-z** [comment]
Fixed as part of [`v0.8.0`](https://github.com/aslafy-z/helm-git/releases). Please have a try!

**Comment by jaroslaw-osmanski** [comment]
@aslafy-z I don't think that https://github.com/aslafy-z/helm-git/pull/106 fixed this. I suppose that using diff plugin changes the way `helm home` works.
