### ISSUE TITLE
Support chart path = root of project?

### ISSUE THREAD

**Issue by bitsofinfo** [aslafy-z/helm-git#15]
What if the chart I want to connect to is the repo itself?

For example my chart source is located at 

`git+ssh://git@git.mydomain.com/my-apps-helm/my-custom-chart@.`

There is no subdirectory within `my-custom-chart/` 

Is this possible?

**Comment by aslafy-z** [comment]
Yes, it is possible like this from now:
```
helm repo add my-custom-chart git+ssh://git@git.mydomain.com/my-apps-helm/my-custom-chart@
```

Leading @ is mandatory, I need to refine the regexp to extract it correctly.

**Comment by bitsofinfo** [comment]
thanks!

**Comment by mojochao** [comment]
I'm trying to use an incubating Traefik 2 chart at https://github.com/containous/traefik-helm-chart which is also a repo where the chart is the repo itself.  I'm trying to add this repo with
```
$ helm repo add traefik2 'git+https://github.com/containous/helm-traefik-chart@?ref=master'
remote: Repository not found.
fatal: repository 'https://github.com/containous/helm-traefik-chart/' not found
Error in plugin 'helm-git': error Unable to sparse-checkout. Check your Git ref (master) and path ().
Error: Looks like "git+https://github.com/containous/helm-traefik-chart@?ref=master" is not a valid chart repository or cannot be reached: plugin "helm-git" exited with error
```
I know it must be user error.  What is the correct way to format the repo add command for this case?

**Comment by jmturwy** [comment]
> Yes, it is possible like this from now:
> 
> ```
> helm repo add my-custom-chart git+ssh://git@git.mydomain.com/my-apps-helm/my-custom-chart@
> ```
> 
> Leading @ is mandatory, I need to refine the regexp to extract it correctly.

What if i need a tag appened to the root chart?

**Comment by aslafy-z** [comment]
@jmturwy these works at my side.

```shell
HELM_GIT_DEBUG=1 helm repo add hashicorp-vault 'git+https://github.com/hashicorp/vault-helm@?ref=v0.5.0'
HELM_GIT_DEBUG=1 helm fetch hashicorp-vault/vault
```

Can you try again and provide the output? Thanks

**Comment by lyz-code** [comment]
Hi @aslafy-z , I have reproduced the error:

```
$: HELM_GIT_DEBUG=1 helm repo add hashicorp-vault 'git+https://github.com/hashicorp/vault-helm@?ref=v0.5.0'
Debug in plugin 'helm-git': repo: https://github.com/hashicorp/vault-helm ref: v0.5.0 path: https://github.com/hashicorp/vault-helm@/index.yaml?ref=v0.5.0 file: https://github.com/hashicorp/vault-helm@/index.yaml?ref=v0.5.0 sparse: 1 depupdate: 1
Debug in plugin 'helm-git': helm_repo_uri: git+https://github.com/hashicorp/vault-helm@https://github.com/hashicorp/vault-helm@/index.yaml?ref=v0.5.0?ref=v0.5.0&sparse=1&depupdate=1
error: Sparse checkout leaves no entry on working directory
Error in plugin 'helm-git': Unable to sparse-checkout. Check your Git ref (v0.5.0) and path (https://github.com/hashicorp/vault-helm@/index.yaml?ref=v0.5.0).
Error: Looks like "git+https://github.com/hashicorp/vault-helm@?ref=v0.5.0" is not a valid chart repository or cannot be reached: plugin "helm-git" exited with error
```

I'm using helm version 2.16.1 and helm-git version 0.10.0.

Thanks!

**Comment by aslafy-z** [comment]
Thanks for reporting @lyz-code, lets follow up on #131
