### ISSUE TITLE
Bug: Doesn't find charts with semantic versioning tags

### ISSUE THREAD

**Issue by sidju** [aslafy-z/helm-git#186]
helm-git fails to recognize charts when their versions end with a pre-release tag, for example 0.0.22 works but 0.0.22-dev fails.

This may be helm failing or blocking pre-release versions (see debug log below), in that case please just say so and close this issue.

`helm-git` version: 0.11.1

## Steps To Reproduce

1. Add [this repo](https://github.com/rancher/local-path-provisioner) both on master branch and on tag 0.0.22
`helm repo add test1 git+https://github.com/rancher/local-path-provisioner@deploy/chart`
`helm repo add test2 git+https://github.com/rancher/local-path-provisioner@deploy/chart?ref=v0.0.22`
2. Search for the chart, local-path-provisioner. If all works as expected both repositories will show a match.

Link to chart repository: https://github.com/rancher/local-path-provisioner
Also, a fork of it without '-dev': https://github.com/sidju/local-path-provisioner

## The current behavior

When adding the repo that seems to work:
```
HELM_GIT_DEBUG=1 helm repo add test1 git+https://github.com/rancher/local-path-provisioner@deploy/chart
Warning in plugin 'helm-git': git_ref is empty, defaulted to 'master'. Prefer to pin GIT ref in URI.
Debug in plugin 'helm-git': repo: https://github.com/rancher/local-path-provisioner ref: master path: deploy/chart file: index.yaml sparse: 1 depupdate: 1 package: 1
Debug in plugin 'helm-git': helm_repo_uri: git+https://github.com/rancher/local-path-provisioner@deploy/chart?ref=master&sparse=1&depupdate=1&package=1
Debug in plugin 'helm-git': helm index produced at /tmp/helm-git.A02pyZ/index.yaml: apiVersion: v1
entries:
  local-path-provisioner:
  - apiVersion: v1
    appVersion: v0.0.22-dev
    created: "2022-04-12T14:18:32.999760431+02:00"
    description: Use HostPath for persistent local storage with Kubernetes
    digest: 80ec586eae8f061937fc49d57cdf89b2e4bfd174e65cbf39662c4319fc2fbe11
    home: https://github.com/rancher/local-path-provisioner
    keywords:
    - storage
    - hostpath
    kubeVersion: '>=1.12.0-r0'
    name: local-path-provisioner
    sources:
    - https://github.com/rancher/local-path-provisioner.git
    urls:
    - git+https://github.com/rancher/local-path-provisioner@deploy/chart/local-path-provisioner-0.0.22-dev.tgz?ref=master&sparse=1&depupdate=1&package=1
    version: 0.0.22-dev
generated: "2022-04-12T14:18:32.999273185+02:00"
"test1" has been added to your repositories
```
But when searching for the chart it isn't found:
```
HELM_GIT_DEBUG=1 helm search repo local-path-provisioner
NAME                        	CHART VERSION	APP VERSION	DESCRIPTION                                       
test2/local-path-provisioner	0.0.22       	v0.0.22    	Use HostPath for persistent local storage with ...
```

## The expected behavior

I would expect it to be possible to add development versions of charts via git, since that is what is likely to reside in git.

**Comment by metajiji** [comment]
Try to add `sparse=0` for `branches` refs.
For example `helm repo add test1 git+https://github.com/rancher/local-path-provisioner@deploy/chart?sparse=0&ref=master`

**Comment by lindhe** [comment]
Please edit the name of this Issue to make it easier to find and understand.

**Comment by sidju** [comment]
Using `helm search repo --devel local-path-provisioner` yields the expected result.

This is not an error in helm-git but a feature in helm that excludes development versions from search results by default.
