### ISSUE TITLE
Minor typo in error message

### ISSUE THREAD

**Issue by TheAnalogyGuy** [aslafy-z/helm-git#238]
https://github.com/aslafy-z/helm-git/blob/master/helm-git-plugin.sh#L59

This line: `    _git_repo="${1?Missing git_repo as first parameer}"`
Should be: `    _git_repo="${1?Missing git_repo as first parameter}"`

**Comment by aslafy-z** [comment]
Thank you, fixed it with [`5a66012`](https://github.com/aslafy-z/helm-git/commit/5a660121596bd13468dc699bd6ddbd3870034ec4)
