### ISSUE TITLE
Bug: git+ssh is broken since 11.0

### ISSUE THREAD

**Issue by NamelessHH** [aslafy-z/helm-git#246]
Since version 0.11.0 git ssh addresses with a path to charts does not work correctly.

Helm version:  3.8.1
`helm-git` version:  0.11.1-0.14.3
Git version:  2.34.1

## Steps To Reproduce

1. run a basic helm add repo with a git+ssh with a path.
2. The example one `git+ssh://git@github.com/jetstack/cert-manager@deploy/charts?ref=v0.6.2` will do 
3. `helm repo add test-cert-manager git+ssh://git@github.com/jetstack/cert-manager@deploy/charts?ref=v0.6.2`

Link to chart repository: 

## The current behavior
```
Error in plugin 'helm-git': No files have been checked out. Check your Git ref (master) and path (github.com/jetstack/cert-manager@deploy/charts).
Error: looks like "git+ssh://git@github.com/jetstack/cert-manager@deploy/charts?ref=master" is not a valid chart repository or cannot be reached: plugin "helm-git" exited with error
```

## The expected behavior

The chart is added.

## Additional information

I'm pretty sure that this line is the [issue](https://github.com/aslafy-z/helm-git/compare/v0.11.0...v0.11.1#diff-828e260a95beb774930f164caa3432d710040c86e3a492fe4ebc5f6ed640b28aR192) 

the problem is that this parser catches the first `@` symbol in a git+ssh address.

**Comment by NamelessHH** [comment]
So I don't know if you want to keep this open but I was apparently using busybox sed instead of gnu sed.  and that was the issue. I'd probably just add it to the documentation. when I installed gnu sed it worked correctly.

**Comment by aslafy-z** [comment]
Thanks for opening this issue. I'd like this project to work with busybox, I'm sure we can do something for it.  PRs are welcome!

**Comment by aslafy-z** [comment]
This issue should be fixed by https://github.com/aslafy-z/helm-git/releases/tag/v0.15.0, can you please have a try?
```shell
helm plugin install https://github.com/aslafy-z/helm-git --version v0.15.0
```
Feel free to re-open this issue if your issue is still present.
