### ISSUE TITLE
Please add "latest" tag to at least one of the releases.

### ISSUE THREAD

**Issue by evanstucker-hates-2fa** [aslafy-z/helm-git#35]
None of the releases has a "latest" tag, which breaks some automation I've got. Would it be possible for you to add a "latest" tag?

For example, see:
https://github.com/chartmuseum/helm-push/releases/latest

Note that helm-git repo doesn't have this tag:
https://github.com/aslafy-z/helm-git/releases/latest

**Comment by aslafy-z** [comment]
Thanks for the head-up. I released the last tag as latest!
