### ISSUE TITLE
Doesnt work when we specify tag name in url

### ISSUE THREAD

**Issue by jvaibhav123** [aslafy-z/helm-git#45]
Hi,

I am trying to use the tag in the helm git url like below and it is throwing out error

HELM_GIT_DEBUG=1 helm repo add log-router git+https://github.com/vmware/kube-fluentd-operator@log-router?ref=v1.10.0

Error:
Debug in plugin 'helm-git': helm_repo_uri: git+https://github.com/vmware/kube-fluentd-operator@log-router?ref=v1.10.0&sparse=1
fatal: update_ref failed for ref 'HEAD': cannot update ref 'refs/heads/master': trying to write non-commit object 5bfffbd2838e8fc1116d31ccd9b36d965954dba1 to branch 'refs/heads/master'
Error in plugin 'helm-git': error Unable to sparse-checkout. Check your Git ref (v1.10.0) and path (log-router).
Error: Looks like "git+https://github.com/vmware/kube-fluentd-operator@log-router?ref=v1.10.0" is not a valid chart repository or cannot be reached: plugin "helm-git" exited with error

Could you please check and confirm if its bug or something i am doing wrong.
I am using latest version of helm-git.

Thanks un advance

Regards,
Vaibhav Joshi

**Comment by aslafy-z** [comment]
Can you try adding `&sparse=0` at the end of the url?

**Comment by jvaibhav123** [comment]
Thanks @aslafy-z after putting the flag the issue has been resolved. Thanks closing this issue
