### ISSUE TITLE
Sparse support for git 2.22

### ISSUE THREAD

**Issue by Nuru** [aslafy-z/helm-git#9]
The plugin fails when `ref` refers to an [annotated tag](https://stackoverflow.com/a/25996877), which is the usual case for GitHub release tags.

For example:
```
helm repo add istio git+https://github.com/istio/istio@install/kubernetes/helm?ref=1.1.4
Error in plugin 'helm-git': error Unable to pull. Check your git_ref and git_path.
```
(By the way, it would be nice if you included the parsed `git_ref` and `git_path` in your error message.)

Digging in deeper, I uncovered this error message:
```
error: cannot update ref 'refs/heads/1.1.4': trying to write non-commit object 5f41cee7af25cb717ecff9a6cb9d8cdf747437d2 to branch 'refs/heads/1.1.4'
```
which lead me to [this StackOverflow post](https://stackoverflow.com/a/45166423) and [this solution](https://stackoverflow.com/a/45166423) and a lot of extra info [here](https://stackoverflow.com/a/41081908). The problem is that the plugin is trying to do a `git pull` into `master`. The solution is to instead to `git fetch` and then `git checkout`, or maybe to do `git clone` instead. (I am not a git expert and do not know the best way to get just the files you want. These are suggestions to help start further investigation.)

**Comment by aslafy-z** [comment]
Thank you for reporting!
I have to push an update that checkout the whole repo if the branch is not master. Haven't found any other way to reference  a path that doesn't exists in the master branch when another branch is selected with sparse checkout. I let you know!

**Comment by Nuru** [comment]
@aslafy-z I have found that `git clone --depth 1 --branch <TAG>` works reliably to clone just the files at that tag. This [SO answer](https://stackoverflow.com/a/52269934/) suggest you can use `file:///` to get just part of the repo after that.

**Comment by bitsofinfo** [comment]
definitely need this please!

**Comment by aslafy-z** [comment]
As a workaround, you can add `sparse=0` parameter at the end of your url to force clone the full repo before building chart.

**Comment by mrtndwrd** [comment]
> (By the way, it would be nice if you included the parsed git_ref and git_path in your error message.)

@nuru you can get some more info when you do 

```
export HELM_GIT_DEBUG=1
```

and run it again.

**Comment by Nuru** [comment]
@mrtndwrd In version 0.3.0 the output was not too helpful. In 0.4.2 the output is better. Here you go:
```
$ export HELM_GIT_DEBUG=1
$ helm repo add istio git+https://github.com/istio/istio@install/kubernetes/helm?ref=1.1.4
Debug in plugin 'helm-git': repo: https://github.com/istio/istio ref: 1.1.4 path: install/kubernetes/helm file: index.yaml sparse: 1
Debug in plugin 'helm-git': helm_repo_uri: git+https://github.com/istio/istio@install/kubernetes/helm?ref=1.1.4&sparse=1
fatal: update_ref failed for ref 'HEAD': cannot update ref 'refs/heads/master': trying to write non-commit object 5f41cee7af25cb717ecff9a6cb9d8cdf747437d2 to branch 'refs/heads/master'
Error in plugin 'helm-git': error Unable to sparse-checkout. Check your Git ref (1.1.4) and path (install/kubernetes/helm).
Error: Looks like "git+https://github.com/istio/istio@install/kubernetes/helm?ref=1.1.4" is not a valid chart repository or cannot be reached: plugin "helm-git" exited with error
```

**Comment by Nuru** [comment]
@aslafy-z This is more urgent now with the release of `git` [version 2.22](https://raw.githubusercontent.com/git/git/master/Documentation/RelNotes/2.22.0.txt)

>  * The filter specification "--filter=sparse:path=<path>" used to
>    create a lazy/partial clone has been removed.  Using a blob that is
>    part of the project as sparse specification is still supported with
>    the "--filter=sparse:oid=<blob>" option.
> 

Now I cannot even use a `ref=SHA` to get around this issue.

**Comment by Nuru** [comment]
Any progress on this?

**Comment by aslafy-z** [comment]
I have no time to try and implement this feature. I'd love to review and merge any PR around this. I'll change position soon and hopefully will get more time.

**Comment by jwlai** [comment]
@Nuru How are you currently continuing to use the helm-git plugin at this time? Did you just downgrade Git (as seen in above merge request) to keep that working?

**Comment by aslafy-z** [comment]
@jwlai you can disable sparse checkout by adding the `sparse=0` flag.

**Comment by aslafy-z** [comment]
@Nuru @jwlai can you please try again with `helm plugin install https://github.com/aslafy-z/helm-git --version 5683385eae278be4709838fdc622513f5d97d947`? Thank you
