### ISSUE TITLE
Does it support gitlab？

### ISSUE THREAD

**Issue by zhaorendong** [aslafy-z/helm-git#94]
I want to user Gitlab ,does it support gitlab？

**Comment by aslafy-z** [comment]
It does, as any other Git repository

**Comment by zhaorendong** [comment]
When I added a repository from gitlab , it error. Questions are as follows：

[root@fet1 docker-build]# 
[root@fet1 docker-build]# helm plugin install https://github.com/aslafy-z/helm-git
Installed plugin: helm-git
[root@fet1 docker-build]# helm plugin list
NAME            VERSION DESCRIPTION                               
helm-git        0.7.0   Get non-packaged Charts directly from Git.
[root@fet1 docker-build]# 
[root@fet1 docker-build]# helm repo add myrepo http://10.34.40.13/root/helm-repository@charts
Error: looks like "http://10.34.40.13/root/helm-repository@charts" is not a valid chart repository or cannot be reached: error converting YAML to JSON: yaml: line 3: mapping values are not allowed in this context
[root@fet1 docker-build]#

**Comment by aslafy-z** [comment]
There is no support for HTTP protocol from now. Created #95 to track this FR.

In the meantime you can use SSH protocol with the `git+ssh://` prefix as seen in the README. Let me know if you need additional help.
